### PR TITLE
Update Platforms to Go 1.10

### PR DESCRIPTION
**Pull request by dave-tucker**
This adds all platforms up to Go 1.9
Tests are updated to support Go versions > 1.5
The OsList and ArchList variables are removed as they appear unused

Signed-off-by: Dave Tucker <dave@dtucker.co.uk>

### CODE REVIEW

**Comment by dave-tucker** [comment]
Related to #93 - I was maintaining this in a fork... but as upstream is now active (and has CI 🎉 ) I thought I'd open a PR here!

**Comment by mattfarina** [comment]
This is a cleanup I wanted to see. Since a couple variables are removed I'm going to give this a good once over and triple check everything.

**Comment by mattfarina** [comment]
FYI, I'm going to wait until after the holidays to merge this. Don't want to accidentally break something for someone right now. I didn't forget about it.

**Comment by ruflin** [comment]
@mattfarina Small ping on this one ;-)

**Comment by Nayana-ibm** [comment]
Curious to know, when this will get merged?

**Comment by Nayana-ibm** [comment]
@ruflin @mitchellh Also, if it supports s390x

**Comment by dave-tucker** [comment]
@ruflin updated to include #107 and add support for 1.10

**Comment by mitchellh** [comment]
Thanks this looks _great_! Thank you so much. Once the tests pass I'll merge this.

**Comment by ruflin** [comment]
Thanks a lot @dave-tucker @mitchellh @mattfarina

**Comment by Nayana-ibm** [comment]
Thanks.. This also covers #85

**Pull request merged**
